#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-EOSQL
DO
\$do\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${MESSENGER_DB_USER}') THEN
    CREATE ROLE ${MESSENGER_DB_USER} LOGIN CREATEDB PASSWORD '${MESSENGER_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${MESSENGER_DB_USER} WITH LOGIN CREATEDB PASSWORD '${MESSENGER_DB_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${KEYCLOAK_DB_USER}') THEN
    CREATE ROLE ${KEYCLOAK_DB_USER} LOGIN PASSWORD '${KEYCLOAK_DB_PASSWORD}';
  ELSE
    ALTER ROLE ${KEYCLOAK_DB_USER} WITH LOGIN PASSWORD '${KEYCLOAK_DB_PASSWORD}';
  END IF;
END
\$do\$;

SELECT 'CREATE DATABASE ${MESSENGER_DB_NAME} OWNER ${MESSENGER_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${MESSENGER_DB_NAME}') \gexec

SELECT 'CREATE DATABASE ${KEYCLOAK_DB_NAME} OWNER ${KEYCLOAK_DB_USER}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${KEYCLOAK_DB_NAME}') \gexec
EOSQL
