ALTER TABLE "ChatMember" DROP CONSTRAINT "ChatMember_chatId_fkey";

ALTER TABLE "Message" DROP CONSTRAINT "Message_chatId_fkey";

ALTER TABLE "ChatMember"
ADD CONSTRAINT "ChatMember_chatId_fkey"
FOREIGN KEY ("chatId") REFERENCES "Chat"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Message"
ADD CONSTRAINT "Message_chatId_fkey"
FOREIGN KEY ("chatId") REFERENCES "Chat"("id") ON DELETE CASCADE ON UPDATE CASCADE;
